name = "api"
main = "src/index.ts"
compatibility_date = "2025-02-13"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

route = { pattern = "api.openfeedback.tech/*", zone_name = "openfeedback.tech" }

[observability]
enabled = true

[[kv_namespaces]]
binding = "OF_STORE"
id = "019d1859a7f64115a889f397093cc94f"